### ISSUE TITLE
ios 10 滚动兼容

### ISSUE THREAD

**Issue by xiezhengyun** [yangg/scrolling-element#1]
博主 ，你好。 移动端iOS 10 微信 里表现差强人意。目前发现两个。
1.遮罩上面如果内容过多，滚动的时候，刚开始的时候是可以滚动的，但是，触摸（上下滚动）了遮罩的内容以外的不可点击区域之后，会出现滚动卡死。
2.当遮罩未出现，而此时页面已经向下滚动了一段距离，此时打开遮罩，下方会出现白色条状。应该是原页面滚动的高度。

最后，目前我很头疼移动端的滚动穿透问题，老是没有一种很好的解决方案。希望，博主能指教下

**Comment by yangg** [comment]
https://uedsky.com/demo/modal-scroll.html
1. 你试了这个 demo 有你说的问题吗？
2. 内容过多是多少结节，多少内容？
3. 你页面的滚动条是不是不是 body，自己用别的元素限制了高度的？

**Comment by xiezhengyun** [comment]
非常感谢您的回答。
1.试了demo没有问题。
2.内容过多是指遮罩上面的内容展现区域内容高度超出盒子高度，即内容超出出现滚动条。
3.至于页面的滚动条，我没有限制其他元素的高度。

最后：例子可供下载吗，希望学习下。

**Comment by yangg** [comment]
https://github.com/yangg/blog/blob/master/source/demo/modal-scroll.html
